config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "posts#index", as: 'home'

  get 'about' => 'pages#about', as: 'about'

  resources :posts do
    resources :comments, only: [:create, :edit, :update, :destroy]
  end  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  validates :username, presence: true, length: {minimum: 5}
  validates :body, presence: true, length: { minimum: 5 }
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments, dependent: :destroy
  validates :title, presence: true, length: { minimum: 5 }
  validates :body, presence: true, length: { minimum: 10 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  # http_basic_authenticate_with name: "lugard", password: "12345678", only: [:destroy]

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params)
    redirect_to post_path(@post)
  end

  def edit
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
  end

  def update
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    if @comment.update(comment_params)
      redirect_to post_path(@post)
    else
      render 'edit'
    end
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    redirect_to post_path(@post) # Redirect to the post show page
  end

  private

  def comment_params
    params.require(:comment).permit(:username, :body)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
    @title = 'About Us'
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # http_basic_authenticate_with name: "lugard", password: "12345678", except: [:index, :show]
  
  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to @post, notice: 'Post was successfully created.'
    else
      render :new
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to @post, notice: 'Post was successfully updated.'
    else
      render :edit
    end  
  end

  def show
    @post = Post.find(params[:id])
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path,  notice: 'Post was successfully deleted.'
  end

  private

  def post_params
    params.require(:post).permit(:title, :body)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<h3>Comments</h3>
<% @post.comments.each do |comment| %>
  <div class="well">
    <div class="comment-align">
      <p><strong><%= comment.username %></strong>: <%= comment.body %></p>
      <div class="button">
        <%= link_to 'Edit', edit_post_comment_path(comment.post, comment), class: 'btn btn-primary btn-sm px-3' %>
        <%= button_to "[X]", post_comment_path(comment.post, comment),
                         method: :delete,
                         data: { confirm: "Are you sure?" },
                         class: "btn btn-danger btn-sm px-3" %>
      </div>
    </div>
  </div>
<% end %>

app/views/comments/_form.html.erb
<h3>Add Comment</h3>
<main class="commentContext">
  <%= form_for([@post, @post.comments.build]) do |f| %>
  <p>
    <%= f.label :username %><br>
    <%= f.text_field :username, class: 'form-control', placeholder: 'Enter your name' %>
  </p>

  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body, class: 'form-control', placeholder: 'Post your reply' %>
  </p>

  <p>
    <%= f.submit 'Create Comment', class: 'btn btn-primary' %>
  </p>
<% end %>
</main>

app/views/comments/edit.html.erb
<h2>Edit Comment</h2>

<%= form_for([@post, @comment]) do |f| %>
  <p>
    <%= f.label :username %><br>
    <%= f.text_field :username, class: 'form-control' %>
  </p>

  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body, class: 'form-control' %>
  </p>

  <p>
    <%= f.submit 'Update Comment', class: 'btn btn-primary' %>
  </p>
<% end %>

<%= link_to 'Back', post_path(@post), class: 'btn btn-secondary' %>

app/views/layouts/_footer.html.erb
<footer class="footer mt-auto py-5">
  <div class="container">
    <span class="text-muted">3pleBlog &copy; 2024.</span>
  </div>
</footer>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default d-flex navbar-custom" style="width: 100%;">
  <div class="navbar-header d-flex justify-content-between align-items-center" style="width: 100%;">
    <a class="navbar-brand" href="#">3pleBlog</a>
    <button class="navbar-toggler d-lg-none" type="button" data-toggle="collapse" data-target="#navbarMenu" aria-controls="navbarMenu" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div id="navbarMenu" class="collapse navbar-collapse d-lg-flex justify-content-end">
      <ul class="nav navbar-nav">
        <li><%= link_to 'Home', home_path, class: 'nav-link text-decoration-none' %></li>
        <li><%= link_to 'CreatePost', new_post_path, class: 'nav-link text-decoration-none' %></li>
        <li><%= link_to 'About', about_path, class: 'nav-link text-decoration-none' %></li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>3pleBlog</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="turbo-visit-control" content="reload">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" %>
  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_include_tag "application", "data-turbo-track": "reload" %>
</head>
<body>
  <%= render 'layouts/navbar' %>
  <div class="pages container-fluid d-flex flex-column min-vh-100">
    <main class="flex-grow-1">
      <%= yield %>
    </main>
  </div>
  <%= render 'layouts/footer' %>

  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
  <%= javascript_include_tag 'mobile_menu', "data-turbo-track": "reload" %>
</body>
</html>

app/views/pages/_aboutContext.html.erb
<main class="aboutContext">
  <h2>Welcome to 3pleBlog!</h2>
<h4>Our Mission</h4>
<p>At 3pleBlog, our mission is to share insights, stories, and knowledge
  that inspire and empower our readers. Whether you're here for advice,
  entertainment, or education, we strive to provide high-quality content
   that caters to your interests and needs.
</p>
<h4>Our Story</h4>
<p>3pleBlog was founded in 2024 by Lugard, with a passion for learning and
   advancing in the areas of "technology and innovation". What started as a
   small personal project has grown into a vibrant community of readers and
   contributors. We are dedicated to maintaining a space where ideas can 
   flourish and conversations can thrive.
</p>
<h4>Meet the Team</h4>
<p>
  We are a diverse group of writers, thinkers, and enthusiasts who are passionate
  about Tech and Innovations. Each member of our team brings a unique perspective
  and expertise, ensuring that our content is both informative and engaging.
</p>
<p>[Lugard] - Founder & Chief Editor</p>
<p>[Team Member 1] - [Role/Title]</p>
<p>[Team Member 2] - [Role/Title]</p>
<h4>What We Offer</h4>
<p>Our blog covers a wide range of topics, including:</p>
<ol type="1">
  <li>HTML5, CSS3, Tailwind, and Bootstrap</li>
  <li>JavaScript</li>
  <li>React and Redux</li>
  <li>Ruby</li>
  <li>Ruby on Rails</li>
</ol>
<p>
  We publish regular articles, how-to guides, opinion pieces, and more to keep you
   informed and entertained.
</p>
<h4>Join Our Community</h4>
<p>
  We believe in the power of community and invite you to be a part of ours. Connect
  with us on [social media platforms] and subscribe to our newsletter for the latest
  updates.
</p>
<h4>Contact Us</h4>
<p>
  We love hearing from our readers! If you have any questions, feedback, or just want
  to say hello, feel free to reach out to us at [agulugard@gmail.com].
</p>
<p>
  Thank you for visiting 3pleBlog. We hope you enjoy your time here and find our content
  both useful and enjoyable.
</p>
</main>

app/views/pages/about.html.erb
<div class="about-page">
  <h1 class="aboutTitle"><%= @title %></h1>
  <%= render 'pages/aboutContext' %>
</div>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>

<%= form_with(model: @post, local: true) do |form| %>

<div>
  <%= form.label :title %><br>
  <%= form.text_field :title %>
</div>
<div>
  <%= form.label :body %><br>
  <%= form.text_area :body %>
</div>
<div>
  <%= form.submit 'Update Post' %>
</div>
<% end %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>Blog Posts</h1>

<div class="row">
  <% @posts.each do |post| %>
    <div class="col-md-6 mb-4">
      <div class="card h-100">
        <div class="card-body">
          <h5 class="card-title"><%= post.title %></h5>
          <p class="card-text"><%= post.body %></p>
          <%= link_to 'Read More', post_path(post), class: 'btn btn-primary' %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/posts/new.html.erb
<h1>Add Post</h1>

<%= form_for @post do |f| %>
  <% if @post.errors.any? %> 
        <% @post.errors.full_messages.each do |message| %>
          <div class="alert alert-danger"><%= message %></div>
        <% end %>
  <% end %>

  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title, placeholder: 'Enter Title', class: 'form-control' %>
  </p>

  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body, placeholder: 'Enter Post', class: 'form-control' %>
  </p>

  <p>
    <%= f.submit 'Create Post', class: 'btn btn-primary' %>
  </p>
<% end %>

<%= link_to 'Prev', posts_path %>

app/views/posts/show.html.erb
<h2>View Post</h2>
<h3><%= @post.title %></h3>
<p><%= @post.body %></p>
<div class="button">
  <%= link_to 'Edit', edit_post_path(@post), class: "btn btn-primary btn-sm" %> |
  <%= button_to "Delete", post_path(@post),
                         method: :delete,
                         data: { confirm: "Really delete?" },
                         class: "btn btn-danger btn-sm" %>
</div>
<hr>

<%= render 'comments/comment' %>
<%= render 'comments/form', post: @post %>